{{- if .Values.arc-runners.enabled }}
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Values.global.runnerGroup }}
  namespace: {{ .Values.namespaces.arcRunners }}
  labels:
    {{- include "arc-runner-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.arc-runners.minRunners }}
  template:
    spec:
      organization: {{ trimPrefix "https://github.com/" .Values.global.githubConfigUrl }}
      group: {{ .Values.global.runnerGroup }}
      labels:
        - self-hosted
        - linux
        - x64
        - {{ .Values.global.runnerGroup }}
      {{- if eq .Values.arc-runners.containerMode.type "dind" }}
      dockerEnabled: true
      dockerdWithinRunnerContainer: true
      {{- end }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ .Values.global.runnerGroup }}-autoscaler
  namespace: {{ .Values.namespaces.arcRunners }}
  labels:
    {{- include "arc-runner-stack.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: {{ .Values.global.runnerGroup }}
  minReplicas: {{ .Values.arc-runners.minRunners }}
  maxReplicas: {{ .Values.arc-runners.maxRunners }}
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "30m"
{{- end }}
