{{- if .Values.clusterSecretStore.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: {{ .Values.namespaces.externalSecrets }}
  labels:
    {{- include "arc-runner-stack.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.managedIdentity.clientId }}
{{- end }}
